nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs
supportedArchitectures: {
  os: [
    "current",
    "darwin",
    "linux",
  ],
  cpu: [
    "current",
    "x64",
  ],
  libc:
    [
      "current",
      "musl"
  ]
}