---
################################################################
# Use this workflow to test your site's GitHub actions locally #
# Use nektos/act: https://github.com/nektos/act                #
################################################################
name: Test workflow
on: push

jobs:
  localtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get prefixPath
        uses: actions/github-script@v6
        id: set-result
        with:
          script: |
            const script = require('./.github/scripts/get-path-prefix.js');
            await script({ core });
          result-encoding: string

      - name: Get result
        run: echo "${{ steps.set-result.outputs.path_prefix }}"
