---
###########################
###########################
## Pull request testing ##
###########################
###########################
name: Test a pull request

#
# Documentation:
# - Workflow syntax: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# - SuperLinter: https://github.com/github/super-linter
# - Markdown linter: https://github.com/DavidAnson/markdownlint

######################################################
# Start the job on a pull request to the main branch #
######################################################
on:
  pull_request:
    branches: [main]

###############
# Set the Job #
###############
jobs:
  lint:
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        #
        # Use full version number to avoid cases when a next
        # released version is buggy
        #
        uses: github/super-linter/slim@v4.9.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          #
          # The Markdown rules are defined at
          # .github/linters/.markdown-lint.yml
          #
          # Documentation on rules:
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'

      - name: Install yarn
        run: corepack enable && yarn set version stable

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false
        with:
          cmd: install # runs `yarn install` command

      - name: Check internal links
        run: yarn test:links

      - name: Build site
        if: ${{ success() }}
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
        env:
          REPO_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
